### ISSUE TITLE
Impact of the data processed by application on open sourcing

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/GSAOpenSourcePolicy#7]
Does the data that the application processes impact its ability to be open sourced, even if that data is not contained in the source code?

For instance an application that handles:
- PII
- credit card numbers
- financial transactions
- human resources data

**Comment by konklone** [comment]
It shouldn't have an impact -- if anything, this would increase the need for the source code to be open. Systems that process credit card transactions and SSNs shouldn't rely on hiding their source code to maintain their security posture.

Login.gov's code, including its PII processing code, has been open source from the beginning of development: https://github.com/18f/identity-idp We view this transparency, including exposing the security-sensitive strategy we've taken with row-level encryption, as critical to enabling robust review of our security architecture and overall public trust in the system.

**Comment by gbinal** [comment]
+1

It's a good question to ask, @rdgsa.  I agree with @konklone - not only do those considerations not impact the ability for a project to be opensourced, they make it more important for the project to be open.  Security through obscurity consistently fails us.  

To expand on something @konklone mentioned, this is also where it is distinctly more useful to get in the habit of starting projects in the open from day one instead of building them  in private with an intention of making them public later.  Not only is the latter path harder and more likely to lead to a decision not to open source something, but the project misses out on the very real benefit of the the openness prodding the developers to do things right the first time and not cut corners that might otherwise blend code and data in a way that causes problems down the road.

**Comment by jcastle-zz** [comment]
Moving all discussion to forked 18F repo for development of overarching GSA guidance - https://github.com/GSA/open-source-policy
